import os
import sqlite3

import psycopg
from psycopg import sql


SQLITE_DB = "hardware_inventory.db"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set.")


TABLE_DEFINITIONS = {
    "users": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT UNIQUE NOT NULL",
        "email TEXT UNIQUE NOT NULL",
        "password_hash TEXT NOT NULL",
        "role TEXT DEFAULT 'STUDENT'",
        "failed_attempts INTEGER DEFAULT 0",
        "is_locked INTEGER DEFAULT 0",
    ],
    "password_resets": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "email TEXT NOT NULL",
        "new_password_hash TEXT NOT NULL",
        "request_date TEXT NOT NULL",
        "status TEXT DEFAULT 'PENDING'",
    ],
    "hardware": [
        "id TEXT PRIMARY KEY",
        "name TEXT NOT NULL",
        "category TEXT NOT NULL",
        "stock_qty INTEGER NOT NULL",
        "unit_price DOUBLE PRECISION DEFAULT 0.0",
        "status TEXT DEFAULT 'In Stock'",
        "condition_status TEXT DEFAULT 'GOOD'",
    ],
    "borrow_records": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "username TEXT NOT NULL",
        "hardware_id TEXT NOT NULL",
        "borrow_qty INTEGER NOT NULL",
        "borrow_date TEXT NOT NULL",
        "return_due_date TEXT",
        "status TEXT DEFAULT 'PENDING'",
        "approved_by TEXT DEFAULT '-'",
        "checked_out_at TEXT",
        "returned_at TEXT",
        "return_condition TEXT",
        "return_notes TEXT",
        "purpose TEXT",
        "instructor TEXT",
        "transaction_id TEXT",
    ],
    "audit_logs": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "action TEXT NOT NULL",
        "details TEXT NOT NULL",
        "performed_by TEXT DEFAULT 'System'",
        "timestamp TEXT NOT NULL",
    ],
    "condition_history": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "hardware_id TEXT NOT NULL",
        "old_condition TEXT NOT NULL",
        "new_condition TEXT NOT NULL",
        "reason TEXT NOT NULL",
        "changed_by TEXT NOT NULL",
        "changed_at TEXT NOT NULL",
    ],
    "inventory": [
        "id TEXT PRIMARY KEY",
        "name TEXT NOT NULL",
        "category TEXT NOT NULL",
        "quantity INTEGER NOT NULL",
        "status TEXT NOT NULL",
    ],
}

IDENTITY_COLUMNS = {
    "users": "id",
    "password_resets": "id",
    "borrow_records": "id",
    "audit_logs": "id",
    "condition_history": "id",
}


def sqlite_table_exists(cursor, table_name):
    cursor.execute(
        "SELECT 1 FROM sqlite_master "
        "WHERE type = 'table' AND name = ?",
        (table_name,),
    )
    return cursor.fetchone() is not None


sqlite_conn = sqlite3.connect(SQLITE_DB)
sqlite_conn.row_factory = sqlite3.Row
pg_conn = psycopg.connect(DATABASE_URL)
pg_conn.autocommit = False

try:
    pg_cur = pg_conn.cursor()
    sqlite_cur = sqlite_conn.cursor()
    counts = {}

    for table_name, columns in TABLE_DEFINITIONS.items():
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)
        pg_cur.execute(
            sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
                sql.Identifier(table_name),
                column_sql,
            )
        )

    for table_name in TABLE_DEFINITIONS:
        if not sqlite_table_exists(sqlite_cur, table_name):
            counts[table_name] = 0
            print(f"Skipping '{table_name}': source table does not exist.")
            continue

        pg_cur.execute(
            sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name))
        )
        if pg_cur.fetchone()[0] > 0:
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")

        sqlite_cur.execute(f'SELECT * FROM "{table_name}"')
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)
        if not rows:
            continue

        source_columns = [description[0] for description in sqlite_cur.description]
        column_identifiers = sql.SQL(", ").join(
            sql.Identifier(column) for column in source_columns
        )
        placeholders = sql.SQL(", ").join(
            sql.Placeholder() for _ in source_columns
        )
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
            sql.Identifier(table_name),
            column_identifiers,
            placeholders,
        )

        for row in rows:
            pg_cur.execute(insert_sql, [row[column] for column in source_columns])

    for table_name, id_column in IDENTITY_COLUMNS.items():
        pg_cur.execute(
            sql.SQL(
                "SELECT setval(pg_get_serial_sequence(%s, %s), "
                "COALESCE(MAX({}), 1), MAX({}) IS NOT NULL) FROM {}"
            ).format(
                sql.Identifier(id_column),
                sql.Identifier(id_column),
                sql.Identifier(table_name),
            ),
            (table_name, id_column),
        )

    pg_conn.commit()
    print("Migration completed successfully.")
    for table_name, count in counts.items():
        print(f"  {table_name}: {count}")
except Exception:
    pg_conn.rollback()
    raise
finally:
    sqlite_conn.close()
    pg_conn.close()
