
import os  # Provides access to operating-system environment variables.[cite: 1]
import sqlite3  # Provides SQLite database access for the original local database.[cite: 1]
import psycopg  # Provides PostgreSQL database access.[cite: 1]
from psycopg import sql  # Provides safe SQL construction for table and column identifiers.[cite: 1]

SQLITE_DB = "hardware_inventory.db"  # Stores the filename of the original SQLite database.[cite: 1]
DATABASE_URL = os.getenv("DATABASE_URL")  # Reads the PostgreSQL connection string from the environment.[cite: 1]

if not DATABASE_URL:  # Checks whether the PostgreSQL connection string was provided.[cite: 1]
    raise RuntimeError("DATABASE_URL is not set.")  # Stops the migration if the connection string is missing.[cite: 1]

sqlite_conn = sqlite3.connect(SQLITE_DB)  # Opens the original SQLite database.[cite: 1]
sqlite_conn.row_factory = sqlite3.Row  # Allows SQLite rows to be accessed by column name.[cite: 1]

pg_conn = psycopg.connect(DATABASE_URL)  # Opens a connection to the Supabase PostgreSQL database.[cite: 1]
pg_conn.autocommit = False  # Uses a transaction so changes can be rolled back if an error occurs.[cite: 1]

try:  # Starts the protected migration section.[cite: 1]
    pg_cur = pg_conn.cursor()  # Creates a PostgreSQL cursor for SQL commands.[cite: 1]
    sqlite_cur = sqlite_conn.cursor()  # Creates a SQLite cursor for reading source data.[cite: 1]

    table_definitions = {  # Defines the PostgreSQL tables required by this application.[cite: 1]
        "users": [  # Defines the users table.[cite: 1]
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the user ID column.[cite: 1]
            "username TEXT UNIQUE NOT NULL",  # Stores each user's unique username.[cite: 1]
            "email TEXT NOT NULL DEFAULT 'user@campus.edu'",  # Stores the user's email address.[cite: 1]
            "password_hash TEXT NOT NULL",  # Stores the hashed password.[cite: 1]
            "role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER'))",  # Restricts the user role.[cite: 1]
            "failed_attempts INTEGER NOT NULL DEFAULT 0",  # Stores the number of failed login attempts.[cite: 1]
            "is_locked INTEGER NOT NULL DEFAULT 0",  # Stores whether the account is locked.[cite: 1]
        ],  # Ends the users column definition list.[cite: 1]
        "password_resets": [  # Defines the password reset request table.[cite: 1]
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the reset request ID.[cite: 1]
            "username TEXT NOT NULL",  # Stores the username requesting the reset.[cite: 1]
            "email TEXT NOT NULL",  # Stores the email used for the request.[cite: 1]
            "new_password_hash TEXT NOT NULL",  # Stores the requested new password hash.[cite: 1]
            "request_time TEXT NOT NULL",  # Stores when the request was created.[cite: 1]
            "status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))",  # Restricts reset status values.[cite: 1]
        ],  # Ends the password reset column definition list.[cite: 1]
        "hardware": [  # Defines the hardware inventory table.[cite: 1]
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the hardware item ID.[cite: 1]
            "item_name TEXT NOT NULL",  # Stores the hardware item name.[cite: 1]
            "category TEXT NOT NULL",  # Stores the hardware category.[cite: 1]
            "quantity INTEGER NOT NULL",  # Stores the available stock quantity.[cite: 1]
            "unit_price DOUBLE PRECISION NOT NULL",  # Stores the price of one unit.[cite: 1]
            "status TEXT NOT NULL",  # Stores the calculated stock status.[cite: 1]
        ],  # Ends the hardware column definition list.[cite: 1]
        "loans": [  # Defines the borrowing and return table.[cite: 1]
            "loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the loan record ID.[cite: 1]
            "username TEXT NOT NULL",  # Stores the borrower username.[cite: 1]
            "item_id BIGINT NOT NULL",  # Stores the borrowed hardware ID.[cite: 1]
            "item_name TEXT NOT NULL",  # Stores the hardware name at the time of borrowing.[cite: 1]
            "borrow_date TEXT NOT NULL",  # Stores the borrow request/borrow date.[cite: 1]
            "return_date TEXT",  # Stores the return date when available.[cite: 1]
            "quantity INTEGER NOT NULL DEFAULT 1",  # Stores how many units were borrowed.[cite: 1]
            "status TEXT NOT NULL DEFAULT 'PENDING_BORROW' CHECK (status IN ('PENDING_BORROW', 'BORROWED', 'RETURN_PENDING', 'RETURNED'))",  # Restricts loan status values.[cite: 1]
        ],  # Ends the loans column definition list.[cite: 1]
    }  # Ends the table definition dictionary.[cite: 1]

    for table_name, columns in table_definitions.items():  # Processes each required application table.[cite: 1]
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)  # Safely combines column definitions.[cite: 1]
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(sql.Identifier(table_name), column_sql)  # Builds the CREATE TABLE statement.[cite: 1]
        pg_cur.execute(create_sql)  # Creates the table if it does not already exist.[cite: 1]

    counts = {}  # Creates a dictionary for recording migrated row counts.[cite: 1]
    for table_name, columns in table_definitions.items():  # Processes each table for data migration.[cite: 1]
        pg_cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name)))  # Checks whether the destination table already has data.[cite: 1]
        destination_count = pg_cur.fetchone()[0]  # Reads the number of existing rows.[cite: 1]
        if destination_count > 0:  # Checks whether the destination table is already populated.[cite: 1]
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")  # Stops to prevent accidental duplicate migration.[cite: 1]

        sqlite_cur.execute(f'SELECT * FROM "{table_name}"')  # SQLite cursors require a rendered SQL string, not psycopg SQL composition objects.[cite: 1]
        rows = sqlite_cur.fetchall()  # Stores the source rows in memory.[cite: 1]
        counts[table_name] = len(rows)  # Records how many rows will be migrated.[cite: 1]
        if not rows:  # Checks whether the source table has no rows.[cite: 1]
            continue  # Moves to the next table when there is nothing to copy.[cite: 1]

        source_columns = [description[0] for description in sqlite_cur.description]  # Gets the SQLite column names.[cite: 1]
        insert_columns = source_columns[:]  # Makes a copy of the source column list for the INSERT statement.[cite: 1]

        if table_name == "loans" and "quantity" not in insert_columns:  # Checks for an older loans table without quantity.[cite: 1]
            insert_columns.append("quantity")  # Adds quantity so older records can still be migrated.[cite: 1]

        column_identifiers = sql.SQL(", ").join(sql.Identifier(column) for column in insert_columns)  # Safely builds the INSERT column list.[cite: 1]
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in insert_columns)  # Creates one PostgreSQL placeholder per value.[cite: 1]
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(sql.Identifier(table_name), column_identifiers, placeholders)  # Builds the INSERT statement.[cite: 1]

        for row in rows:  # Processes every source row.[cite: 1]
            values = [row[column] for column in source_columns]  # Gets the source values in column order.[cite: 1]
            if table_name == "loans" and "quantity" not in source_columns:  # Checks again for legacy loan records.[cite: 1]
                values.append(1)  # Gives older loan records a default quantity of one.[cite: 1]
            pg_cur.execute(insert_sql, values)  # Inserts the current row into PostgreSQL.[cite: 1]

    sequence_columns = {  # Maps each table to its identity ID column.[cite: 1]
        "users": "id",  # Identifies the users primary key column.[cite: 1]
        "password_resets": "request_id",  # Identifies the password reset primary key column.[cite: 1]
        "hardware": "item_id",  # Identifies the hardware primary key column.[cite: 1]
        "loans": "loan_id",  # Identifies the loan primary key column.[cite: 1]
    }  # Ends the identity column mapping.[cite: 1]

    for table_name, id_column in sequence_columns.items():  # Processes each identity column.[cite: 1]
        sequence_sql = sql.SQL("SELECT setval(pg_get_serial_sequence({}, {}), COALESCE(MAX({}), 0), MAX({}) IS NOT NULL) FROM {}").format(  # Builds SQL to synchronize the identity sequence with the migrated IDs.[cite: 1]
            sql.Literal(table_name),  # Supplies the table name as a SQL value.[cite: 1]
            sql.Literal(id_column),  # Supplies the ID column name as a SQL value.[cite: 1]
            sql.Identifier(id_column),  # Supplies the ID column as an SQL identifier for MAX.[cite: 1]
            sql.Identifier(id_column),  # Supplies the ID column again for the sequence state test.[cite: 1]
            sql.Identifier(table_name),  # Supplies the table name as an SQL identifier.[cite: 1]
        )  # Finishes the sequence SQL construction.[cite: 1]
        pg_cur.execute(sequence_sql)  # Updates the identity sequence after explicit IDs were inserted.[cite: 1]

    pg_conn.commit()  # Permanently saves all migrated tables and rows.[cite: 1]
    print("Migration completed successfully.")  # Reports that the migration finished.[cite: 1]
    print(f"  users:            {counts['users']}")  # Displays the number of migrated users.[cite: 1]
    print(f"  password_resets:  {counts['password_resets']}")  # Displays the number of migrated reset requests.[cite: 1]
    print(f"  hardware:         {counts['hardware']}")  # Displays the number of migrated hardware records.[cite: 1]
    print(f"  loans:             {counts['loans']}")  # Displays the number of migrated loan records.[cite: 1]

except Exception:  # Catches any error during migration.
    pg_conn.rollback()  # Cancels PostgreSQL changes made during the failed transaction.
    raise  # Re-raises the original error so the student can see the problem.
finally:  # Runs cleanup whether migration succeeds or fails.
    sqlite_conn.close()  # Closes the SQLite database connection.
    pg_conn.close()  # Closes the PostgreSQL database connection.